# -*- coding: utf-8 -*-
"""numpy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZS4bKHPvAHSPAjHcnJuuOFKstFmLNRa4
"""

import numpy as np
a = np.array([1, 2, 3])  # Create a rank 1 array
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print (a)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))